### PR TITLE
Update OSD Lyrics' home URL

### LINKED ISSUE #22: configure links to code.google.com
At the end of `./configure`'s output the following is written:

> Report bugs to <http://code.google.com/p/osd-lyrics/issues/list>.

This should probably be changed to https://github.com/osdlyrics/osdlyrics/issues

### PR DESCRIPTION
**Pull request by Corax26**
Fixes #22.

I'm not sure why the URL is marked as translatable, but I'm not sure how the *.po files are generated either so in doubt I chose the easy path (i.e. sed)...

---
This change is [Reviewable](https://reviewable.io/reviews/osdlyrics/osdlyrics/27)

### CODE REVIEW

**Comment by tigersoldier** [comment]
You can mark the URLs untranslatable. I don't recall any reason why they are translated, probably due to my lack of knowledge on i18n.

**Comment by Corax26** [comment]
OK, but I'm not familiar with the .po files, how should I edit them? They refer to files/line numbers, so they look generated, but I don't know how...

**Comment by PedroHLC** [comment]
I think, this can help: https://en.wikipedia.org/wiki/Gettext

**Comment by Corax26** [comment]
Oh yes that's helpful, thanks, already came across gettext but I didn't even know what it was for! Now the second thing that confuses me is that a lot of translations (including this one) refer to `dialogs.glade.h`, but I don't see any header generated from `dialogs.glade`?

**Comment by PedroHLC** [comment]
Glade is the format used by a GTK+ window modeler tool, I believe it can be used standalone with libglade, and probably generated from [this file](/osdlyrics/osdlyrics/blob/legacy/data/dialogs.glade). [Here](/osdlyrics/osdlyrics/blob/master/data/Makefile.am) I think it's where it's generated.

**Comment by Corax26** [comment]
Updated the PR to make the string non-translatable and remove the translations.

**Comment by PedroHLC** [comment]
Pushed to master using fast-forward

**Pull request merged**
