### PR TITLE
Fixes for saved UI position (OSD + scroll module)

### PR DESCRIPTION
**Pull request by Corax26**
After almost exactly 4 years, finally creating a PR for this couple of patches :D Each solves a bug with restoring the position of a UI element (OSD and scroll module).

### CODE REVIEW

**Review by PedroHLC — APPROVED** [review]
Getting some trouble with D-Bus in NixOS, but the code looks good and I was at least capable to build it, feel free to merge it!

**Comment by Corax26** [comment]
Cool thanks! Just one thing, why have we configured the repo so that PRs must be squashed into one commit? It doesn't make much sense here, I'd rather keep each commit separate.

**Comment by PedroHLC** [comment]
> Cool thanks! Just one thing, why have we configured the repo so that PRs must be squashed into one commit? It doesn't make much sense here, I'd rather keep each commit separate.

While keeping them separated is better for git-based development, keeping them squashed is better for GitHub-based development, we can go back to the original PR (through the link it adds in the final of the commit title), see the original commits and any comment added during review.

Think you can work with this? Otherwise, I can revert this, since your contribution is more important than a decision like this :sweat_smile:

**Comment by Corax26** [comment]
Right I'm much more of a Git person than a GitHub person I guess :D But I don't think we have to choose between one or the other: in the default workflow, you end up with a merge commit with the description of this PR, while keeping the individual commits. I tend to bundle commits together in a single PR with each doing something "atomic", so I don't like them getting squashed.

**Comment by PedroHLC** [comment]
Ok, should be fixed.

**Comment by PedroHLC** [comment]
@Corax26 please rebase your PR, the commit history looks weird, your PR should be new 2 on top, right now it's below other 35 that are on master branch.

PS: I'm about to add a commit to hardcode the version in OL_BUILD_VER to fix #110 (and I'll do it again after every release)

**Pull request merged**
