### PR TITLE
lyrics: upgrade Chinese encodings (gb18030, big5hkscs) (#128)

### LINKED ISSUE #128: Problematic rendering Chinese characters in GB18030 file
When rendering `.lrc` file with GB18030 encoding, some (many) characters outside GB2312 can not be rendered correctly -- they are displayed as blocked question marks, like the screenshot below:

图片

(Maybe the exact appearance differs with font. I'm not sure.)

I believe this affects all characters outside GB2312, e.g. `镕`, `葉`.

This is accidentally discovered, as most of my lyrics are in UTF-8, which are rendered correctly.

### PR DESCRIPTION
**Pull request by gumblex**
Fix #128 by upgrading the detected Chinese encodings to more recent versions.

### CODE REVIEW

**Comment by kbsky** [comment]
This change seems fine to me but what I know about Chinese encodings is only what I've managed to gather on Wikipedia in the past 5 min so this is really not an expert opinion! Is my understanding correct that GB18030 is a strict superset of GBK and GB2312 (and similarly Big5 HKSCS of Big5)? I struggle to understand why chardet bothers detecting such subsets at all, it doesn't look like that can be configured so I guess we need to have this sort of hack...

**Comment by kbsky** [comment]
Ah, in fact, it turns out [chardet 5.1.0](https://github.com/chardet/chardet/releases/tag/5.1.0) added precisely that functionality (`should_rename_legacy` argument)! Their documentation has not been updated accordingly. In any case 5.1.0 is way too recent for us to be able to use it, the latest Ubuntu release doesn't even ship 5.0 for instance.

**Comment by gumblex** [comment]
GBK, GB18030 are both strict supersets of GB2312. GB18030 is a not-so-strict superset of GBK (differences are a few rare characters). GBK is a non-standard extension of GB2312 in widely use. GB18030 is the current national standard of China, and supports all Unicode characters. Therefore, we can upgrade GB2312 to GB18030 blindly.

Big5 is the old Traditional Chinese encoding. It has many extensions in the past. HKSCS is currently the most accepted extension and the standard of Hong Kong. See [Firefox bug discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=912470#c88).

**Review by PedroHLC — APPROVED** [review]
Code-wise, it looks good to me.

Really amazing simple solution that I would never be aware of.

**Comment by PedroHLC** [comment]
Can I merge it @gumblex ?

**Comment by gumblex** [comment]
I think there is no problem.

**Pull request merged**
