### PR TITLE
0 compile-time C warnings

### PR DESCRIPTION
**Pull request by dasj19**
The purpose of this PR is to eliminate all the compile-time warnings often generated by deprecations.

This PR applies mostly one change over and over throughout many files. The change is described in detail here: https://sigquit.wordpress.com/2009/02/13/avoid-g_type_instance_get_private-in-gobjects/

To be merged after https://github.com/osdlyrics/osdlyrics/pull/96

### CODE REVIEW

**Comment by dasj19** [comment]
I noticed that there are still quite a handful of deprecation warnings related to C-files in the CI build log. This is because the app is compiled with a newer version of Glib than the one I used. (the library glib-dbus-1)... so the next step would be to address those

**Comment by PedroHLC** [comment]
Hi @dasj19, can you rebase this one?

**Comment by dasj19** [comment]
@PedroHLC, done. It is rebased now.

**Review by PedroHLC — APPROVED** [review]
I did a QA test, and everything seems to be working fine here.
Is it ready to merge on your side?

**Comment by dasj19** [comment]
I tested as well and did not find any issues. I think it is ready for merge.

**Pull request merged**
