### PR TITLE
0 obsolete warnings during build

### PR DESCRIPTION
**Pull request by dasj19**
The purpose of this change is to update autoconf calls to obsolete commands, and have a cleaner build in the end.
More details in the commit messages.

This is one small step towards better maintainability of the code in the future.

To-do next: Resolve deprecation warnings

### CODE REVIEW

**Comment by PedroHLC** [comment]
This is an awesome effort man :smile:

**Comment by dasj19** [comment]
> This is an awesome effort man smile

;) now I got the CI to build as well, nice having it as an extra checking tool.

**Comment by PedroHLC** [comment]
Hi @dasj19 is there something else you want to push here, or is it ready for reviewing?

**Comment by dasj19** [comment]
> Hi @dasj19 is there something else you want to push here, or is it ready for review?

It is ready for review. I some other things coming but that is another PR

**Comment by dasj19** [comment]
@PedroHLC did you had a chance to look at / test the new changes?

**Review by PedroHLC — APPROVED** [review]
LGTM!!
Sorry for the late reply, too many things going on right now.

**Pull request merged**
