### PR TITLE
Support Py2&3 in one codebase

### PR DESCRIPTION
**Pull request by pjw91**
This is a supplement of #17, it fixes the searching and downloading of ViewLyrics.

- [x] Fix querying ViewLyrics.com
- [x] Fix downloading from ViewLyrics.com
- [x] Fix writing lrc to file
- [x] The filename of HTTP player `http.py` is conflicting with the Py3 stdlib `http` package
	It requires a new name. Any suggestion?
- [x] Make it Py26+ and Py34+ compatible, eliminates the need of `2to3`
- [x] Test on Py2.7 (Ubuntu 14.04)
- [x] Test on Py3.4 (Ubuntu 14.04)
- [x] Bugs?
  - [x] Ambiguous Metadata.tracknum: either int or string(`%d` or `%d/%d`)
  - [x] Ambiguous Metadata.length: ms or us?
  - [x] players(http,mpd): self._metadata must be dict, not Metadata #29 
- ~~[ ] Ambiguity~~, they don't cause any bug currently
  - ~~[ ] Inconsistency: Python `metadata_equal` vs C `ol_metadata_equal`~~
  - ~~[ ] What if both args of `metadata_equal` are None? Should the result be True or False~~
  - ~~[ ] metadata "false value" ambiguity: `None` and/or empty string?~~

---
This change is [Reviewable](https://reviewable.io/reviews/osdlyrics/osdlyrics/45)

### CODE REVIEW

**Comment by PedroHLC** [comment]
Hi @pjw91 , how is the state of this PR?

**Comment by pjw91** [comment]
In my case, it works.

Please give me some suggestions about the new name of `http.py`, then this PR is all done.

**Comment by PedroHLC** [comment]
If you mean `players/http/http.py` most of them reuse the components name. Considering the component name is the name of their protocol the most polite way would be to rename them all, could be `model.py` or `main.py` or even `@-player.py` (where @ is the folder name)

**Comment by pjw91** [comment]
Ok, I need some time testing.

**Comment by PedroHLC** [comment]
:smile:  hello @pjw91 with the python2's EOL, is it interesting for us to still have py2 support?
Arch, for example, is [killing support](https://www.archlinux.org/todo/die-python2-die) for it.

**Comment by pjw91** [comment]
Tested players: mpris, mpris2
Tested lyricsources: netease, viewlyrics (lrc123 & xiami had not worked.)

---
Regarding Python2, I think we can support Python2, until there's an issue that is not easy to fix. (I mean, if there's a bug that needs to be fixed with `if sys.version_info...`, then we don't fix it and kill support of Py2.)

In this PR, the codebase itself is in Python3. And a 3rd-party package, `future`, which does nothing in Python3, is used to backport Py3 features to Py2. With the import(s) from `future`, this repo supports both Py2&3; without those import(s), as the following demonstrates, it only supports Py3.

If a package maintainer only wants to support Python3 or don't want to introduce more dependencies, (s)he can:
1. `sed '/^from future /d;/^from builtins /d;/^from __future__ /d' **/*.py`.
2. (optionally) revise `if sys.version_info` blocks in `python/utils.py` and `python/dbusext/service.py`.

The first step drops the usage of `future`, thus, strips off the dependent on `python-future`.

**Comment by pjw91** [comment]
___
*[daemon/ini_config.py, line 283 at r1](https://reviewable.io/reviews/osdlyrics/osdlyrics/45#-Lb4lu_h-b1iRmMYbPrE:-Lb6mr8B5e3HVvf9gEqn:b-3wkej) ([raw file](https://github.com/osdlyrics/osdlyrics/blob/0d45c358c0ebdb4a3359a4e15c2f68b1cc6520f5/daemon/ini_config.py#L283)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

What is this comment about?
</blockquote></details>

This's a maker to make flake8 linter ignoring the specific error.

Code F841 is "Local variable name is assigned to but never used".

**Comment by pjw91** [comment]
___
*[daemon/lyrics.py, line 208 at r1](https://reviewable.io/reviews/osdlyrics/osdlyrics/45#-Lb4nQWX4YgbQYsCBHYn:-Lb6pFoDBaDrvaWRMA4M:bhyxtha) ([raw file](https://github.com/osdlyrics/osdlyrics/blob/0d45c358c0ebdb4a3359a4e15c2f68b1cc6520f5/daemon/lyrics.py#L208)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

That's bizarre, but python is bizarre..
</blockquote></details>

Python prefers explicit. "Explicit is better than implicit."

Python2 uses both "0"-prefixed and "0o"-prefixed numeric literals as octal numbers; where Python3 only use "0o"-prefixed numeric literals to represent octals.

**Comment by PedroHLC** [comment]
Fell free to push the merge button 🤓

**Pull request merged**
